"""added comments to task history

Revision ID: a151f5e84247
Revises: 9f0e9a9394bc
Create Date: 2026-07-06 10:19:58.130132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a151f5e84247'
down_revision: Union[str, Sequence[str], None] = '9f0e9a9394bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'comment')
    # ### end Alembic commands ###
