"""rename task assignment columns

Revision ID: dfa9cce88a43
Revises: 772f23cc918e
Create Date: 2026-06-30 18:52:45.487237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa9cce88a43'
down_revision: Union[str, Sequence[str], None] = '772f23cc918e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_team_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('tasks_current_user_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_current_team_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'teams', ['assigned_team_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])
    op.drop_column('tasks', 'current_user_id')
    op.drop_column('tasks', 'current_team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('current_team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('current_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_current_team_id_fkey'), 'tasks', 'teams', ['current_team_id'], ['id'])
    op.create_foreign_key(op.f('tasks_current_user_id_fkey'), 'tasks', 'users', ['current_user_id'], ['id'])
    op.drop_column('tasks', 'assigned_user_id')
    op.drop_column('tasks', 'assigned_team_id')
    # ### end Alembic commands ###
